spring.application.name=backend

# Cambia "teleplus" por el nombre de tu base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/teleplus
# Cambia "postgres" por tu nombre de usuario de PostgreSQL
spring.datasource.username=postgres
# Cambia "password" por tu contrase�a de PostgreSQL
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

